# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/recommendation_db
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis
spring.redis.host=localhost
spring.redis.port=6379